server:
  port: 7001

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password :
    timeout: 30000
    database: 0

  datasource:
    url: jdbc:mysql://localhost:3306/elf
    username: elfadmin
    password: elfadmin
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

mybatis:
  mapper-locations: classpath:mapping/*.xml
